Global:
  model: Deeplabv3-R50
  mode: check_dataset # check_dataset/train/evaluate
  dataset_dir: "/paddle/dataset/paddlex/seg/seg_optic_examples"
  device: gpu:0,1,2,3
  output: "output"

CheckDataset:
  dst_dataset_name: dataset
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  epochs_iters: 500
  num_classes: 2
  batch_size: 2
  learning_rate: 0.01
  pretrain_weight_path: null
  warmup_steps: 0
  resume_path: null
  log_interval: 10
  eval_interval: 100

Evaluate:
  weight_path: "output/best_model/model.pdparams"
  log_interval: 10
