Global:
  model: CLIP_vit_large_patch14_224
  mode: check_dataset # check_dataset/train/evaluate
  dataset_dir: "/paddle/dataset/paddlex/cls/cls_flowers_examples"
  device: gpu:0,1,2,3
  output: "output"

CheckDataset:
  dst_dataset_name: dataset
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  num_classes: 102
  epochs_iters: 20
  batch_size: 64
  learning_rate: 0.0003
  pretrain_weight_path: null
  warmup_steps: 5
  resume_path: null
  log_interval: 1
  eval_interval: 1
  save_interval: 1

Evaluate:
  weight_path: "output/best_model.pdparams"
  log_interval: 1
