Global:
  model: Mask-RT-DETR-L
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "/paddle/dataset/paddlex/instance_seg/instance_seg_coco_examples/"
  device: gpu:0,1,2,3
  output: "output"

CheckDataset:
  convert: 
    enable: False
    src_dataset_type: nul
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  num_classes: 2
  epochs_iters: 40
  batch_size: 2
  learning_rate: 0.0001
  pretrain_weight_path: null
  warmup_steps: 100
  resume_path: null
  log_interval: 10
  eval_interval: 1

Evaluate:
  weight_path: "output/best_model.pdparams"
  log_interval: 10

Predict:
  model_dir: "output/best_model"
  input_path: "/paddle/dataset/paddlex/instance_seg/instance_seg_coco_examples/images/aircraft-women-fashion-pilot-48797.png"
  kernel_option:
    run_mode: paddle
    batch_size: 1