Global:
  model: Mask-RT-DETR-H
  mode: check_dataset # check_dataset/train/evaluate
  dataset_dir: "/paddle/dataset/paddlex/instance_seg"
  device: gpu:0,1,2,3
  output: "output"

CheckDataset:
  dst_dataset_name: dataset
  convert: 
    enable: False
    src_dataset_type: nul
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  num_classes: 2
  epochs_iters: 40
  batch_size: 2
  learning_rate: 0.00005
  pretrain_weight_path: null
  warmup_steps: 100
  resume_path: null
  log_interval: 10
  eval_interval: 1

Evaluate:
  weight_path: "output/best_model.pdparams"
  log_interval: 10